# Generated by Django 5.0.4 on 2024-04-24 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name_category',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
